require("packer-config")
require("cmp-config")
require("lspconfig-config")
require("bufferline-config")
require("lualine-config")
require("nvim-tree-config")
require("telescope-config")
require("toggleterm-config")
require("treesitter-config")
require("vgit-config")
require("vim-config")
require("null-ls-config")
require("nvim-comment-config")
require("keymaps-config")

-- Theme
require("catppuccin").load()
